In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import  seaborn as sns

In [2]:
amazon = pd.ExcelFile("Amazon_Sales_DB.xlsx")

print(amazon.sheet_names)

['Customers', 'Products', 'Categories', 'Orders', 'Order_Items', 'Payments', 'Reviews']

In [3]:
flipkart = pd.ExcelFile("Flipkart_Sales_DB.xlsx")

print(flipkart.sheet_names)

['Customers', 'Products', 'Categories', 'Orders', 'Order_Items', 'Payments', 'Reviews']

In [5]:
a_c_df = pd.read_excel("Amazon_Sales_DB.xlsx", sheet_name = "Customers")
print(a_c_df.shape)

a_p_df = pd.read_excel("Amazon_Sales_DB.xlsx", sheet_name = "Products")
print(a_p_df.shape)

a_cat_df = pd.read_excel("Amazon_Sales_DB.xlsx", sheet_name = "Categories")
print(a_cat_df.shape)

a_o_df = pd.read_excel("Amazon_Sales_DB.xlsx", sheet_name = "Orders")
print(a_o_df.shape)

a_oi_df = pd.read_excel("Amazon_Sales_DB.xlsx", sheet_name = "Order_Items")
print(a_oi_df.shape)

a_pay_df = pd.read_excel("Amazon_Sales_DB.xlsx", sheet_name = "Payments")
print(a_pay_df.shape)

a_r_df = pd.read_excel("Amazon_Sales_DB.xlsx", sheet_name = "Reviews")
print(a_r_df.shape)

(12000, 8)
(2500, 6)
(500, 4)
(18000, 7)
(25000, 6)
(18000, 5)
(5958, 6)

In [6]:
f_c_df = pd.read_excel("Flipkart_Sales_DB.xlsx", sheet_name = "Customers")
print(f_c_df.shape)

f_p_df = pd.read_excel("Flipkart_Sales_DB.xlsx", sheet_name = "Products")
print(f_p_df.shape)

f_cat_df = pd.read_excel("Flipkart_Sales_DB.xlsx", sheet_name = "Categories")
print(f_cat_df.shape)

f_o_df = pd.read_excel("Flipkart_Sales_DB.xlsx", sheet_name = "Orders")
print(f_o_df.shape)

f_oi_df = pd.read_excel("Flipkart_Sales_DB.xlsx", sheet_name = "Order_Items")
print(f_oi_df.shape)

f_pay_df = pd.read_excel("Flipkart_Sales_DB.xlsx", sheet_name = "Payments")
print(f_pay_df.shape)

f_r_df = pd.read_excel("Flipkart_Sales_DB.xlsx", sheet_name = "Reviews")
print(f_r_df.shape)

(12000, 8)
(2500, 6)
(500, 4)
(18000, 7)
(25000, 6)
(18000, 5)
(5986, 6)

## Amazon Data Cleaning and Pre-Processing

### Data Cleaning Process in Customers DataFrame

In [7]:
a_c_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  12000 non-null  object
 1   first_name   12000 non-null  object
 2   last_name    12000 non-null  object
 3   email        12000 non-null  object
 4   phone        12000 non-null  object
 5   city         10948 non-null  object
 6   country      12000 non-null  object
 7   created_at   12000 non-null  object
dtypes: object(8)
memory usage: 750.1+ KB

In [8]:
# Checking Data Types
a_c_df.dtypes

customer_id    object
first_name     object
last_name      object
email          object
phone          object
city           object
country        object
created_at     object
dtype: object

In [9]:
# Checking Duplicate Values
a_c_df.duplicated().sum()

np.int64(0)

In [10]:
# Checking Missing Values
a_c_df.isnull().sum()

customer_id       0
first_name        0
last_name         0
email             0
phone             0
city           1052
country           0
created_at        0
dtype: int64

In [11]:
# Handling Missing Values
a_c_df.dropna(subset=['city'], inplace=True)

In [12]:
a_c_df.isnull().sum()

customer_id    0
first_name     0
last_name      0
email          0
phone          0
city           0
country        0
created_at     0
dtype: int64

### Data Cleaning Process in Amazon - Products DataFrame

In [13]:
a_p_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      2500 non-null   object
 1   product_name    2500 non-null   object
 2   category_id     2500 non-null   object
 3   price           2500 non-null   float64
 4   stock_quantity  2500 non-null   int64
 5   description     2500 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 117.3+ KB

In [14]:
a_p_df.describe()

              price  stock_quantity
count   2500.000000     2500.000000
mean    6781.219128      255.227600
std    14415.366255      143.847794
min       31.760000        0.000000
25%      701.845000      129.000000
50%     1719.240000      257.000000
75%     5268.652500      379.000000
max    79799.430000      500.000000

In [15]:
a_p_df.duplicated().sum()

np.int64(0)

In [16]:
a_p_df.isnull().sum()

product_id        0
product_name      0
category_id       0
price             0
stock_quantity    0
description       0
dtype: int64

In [17]:
a_p_df.dtypes

product_id         object
product_name       object
category_id        object
price             float64
stock_quantity      int64
description        object
dtype: object

### Data Cleaning Process in Orders DataFrame

In [18]:
a_o_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       18000 non-null  object
 1   customer_id    18000 non-null  object
 2   order_date     18000 non-null  object
 3   eta_days       18000 non-null  int64
 4   delivery_date  18000 non-null  object
 5   order_status   16435 non-null  object
 6   total_amount   18000 non-null  float64
dtypes: float64(1), int64(1), object(5)
memory usage: 984.5+ KB

In [19]:
# Correcting Data types
a_o_df['order_date'] = pd.to_datetime(a_o_df['order_date'])

a_o_df['delivery_date'] = pd.to_datetime(a_o_df['delivery_date'])

In [20]:
a_o_df.duplicated().sum()

np.int64(0)

In [21]:
a_o_df.isnull().sum()

order_id            0
customer_id         0
order_date          0
eta_days            0
delivery_date       0
order_status     1565
total_amount        0
dtype: int64

In [22]:
a_o_df['order_status'] = a_o_df['order_status'].fillna('Unknown')

In [23]:
a_o_df.isnull().sum()

order_id         0
customer_id      0
order_date       0
eta_days         0
delivery_date    0
order_status     0
total_amount     0
dtype: int64

### Data Cleaning Process in Ordered Items DataFrame

In [25]:
a_oi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  25000 non-null  object
 1   order_id       25000 non-null  object
 2   product_id     25000 non-null  object
 3   quantity       25000 non-null  int64
 4   unit_price     25000 non-null  float64
 5   total_price    25000 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ MB

In [26]:
a_oi_df.describe()

           quantity    unit_price    total_price
count  25000.000000  25000.000000   25000.000000
mean       3.002960   6864.361615   20348.255441
std        1.412626  14611.103378   48183.619793
min        1.000000     31.760000      31.760000
25%        2.000000    704.680000    1750.600000
50%        3.000000   1731.030000    4659.140000
75%        4.000000   5291.820000   14366.400000
max        5.000000  79799.430000  398854.550000

In [27]:
a_oi_df.duplicated().sum()

np.int64(0)

In [28]:
a_oi_df.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
total_price      0
dtype: int64

### Data Cleaning Process in Payments DataFrame

In [29]:
a_pay_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      18000 non-null  object
 1   order_id        18000 non-null  object
 2   payment_method  16351 non-null  object
 3   payment_date    18000 non-null  object
 4   payment_status  18000 non-null  object
dtypes: object(5)
memory usage: 703.3+ KB

In [30]:
a_pay_df.describe()

,payment_id,order_id,payment_method,payment_date,payment_status
count,18000,18000,16351,18000,18000
unique,18000,18000,5,11271,2
top,PAY-100000,ORD-2026-10000,Cash on Delivery,2024-12-25 07:48:00,Completed
freq,1,1,3319,9,16229

In [31]:
a_pay_df.duplicated().sum()

np.int64(0)

In [32]:
a_pay_df.isnull().sum()

payment_id           0
order_id             0
payment_method    1649
payment_date         0
payment_status       0
dtype: int64

In [34]:
# 1. Calculate the probability distribution of existing payment methods
probabilities = a_pay_df['payment_method'].value_counts(normalize=True)

# 2. Count how many missing values need filling
num_nulls = a_pay_df['payment_method'].isna().sum()

# 3. Randomly sample payment methods matching the exact probability weights
sampled_payments = np.random.choice(probabilities.index, size=num_nulls, p=probabilities.values)

# 4. Fill the null entries
a_pay_df.loc[a_pay_df['payment_method'].isna(), 'payment_method'] = sampled_payments

In [35]:
a_pay_df.isnull().sum()

payment_id        0
order_id          0
payment_method    0
payment_date      0
payment_status    0
dtype: int64

### Data Cleaning Process in Reviews DataFrame

In [36]:
a_r_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5958 entries, 0 to 5957
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    5958 non-null   object
 1   product_id   5958 non-null   object
 2   customer_id  5958 non-null   object
 3   rating       5431 non-null   float64
 4   review_text  5958 non-null   object
 5   review_date  5958 non-null   object
dtypes: float64(1), object(5)
memory usage: 279.4+ KB

In [37]:
a_r_df.describe()

            rating
count  5431.000000
mean      3.007918
std       1.412432
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       5.000000

In [38]:
a_r_df.duplicated().sum()

np.int64(0)

In [39]:
a_r_df.isnull().sum()

review_id        0
product_id       0
customer_id      0
rating         527
review_text      0
review_date      0
dtype: int64

In [41]:
a_r_df['rating'].value_counts()

rating
4.0    1124
3.0    1102
1.0    1095
5.0    1073
2.0    1037
Name: count, dtype: int64

In [45]:
a_r_df.dropna(subset=['rating'], inplace=True)

## Flipkart Data Cleaning and Pre-Processing

### Data Cleaning Process in Customers DataFrame

In [48]:
f_c_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  12000 non-null  object
 1   first_name   12000 non-null  object
 2   last_name    12000 non-null  object
 3   email        12000 non-null  object
 4   phone        12000 non-null  object
 5   city         10914 non-null  object
 6   country      12000 non-null  object
 7   created_at   12000 non-null  object
dtypes: object(8)
memory usage: 750.1+ KB

In [49]:
f_c_df.duplicated().sum()

np.int64(0)

In [50]:
f_c_df.isnull().sum()

customer_id       0
first_name        0
last_name         0
email             0
phone             0
city           1086
country           0
created_at        0
dtype: int64

In [51]:
# Handling Missing Values
f_c_df.dropna(subset=['city'], inplace=True)

In [52]:
f_c_df.isnull().sum()

customer_id    0
first_name     0
last_name      0
email          0
phone          0
city           0
country        0
created_at     0
dtype: int64

### Data Cleaning Process in Products DataFrame

In [53]:
f_p_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      2500 non-null   object
 1   product_name    2500 non-null   object
 2   category_id     2500 non-null   object
 3   price           2500 non-null   float64
 4   stock_quantity  2500 non-null   int64
 5   description     2500 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 117.3+ KB

In [54]:
f_p_df.describe()

              price  stock_quantity
count   2500.000000     2500.000000
mean    7841.360404      402.361200
std    16456.943758      227.744914
min       35.380000       10.000000
25%      864.767500      205.750000
50%     2038.970000      406.000000
75%     6082.030000      594.000000
max    94685.550000      800.000000

In [55]:
f_p_df.duplicated().sum()

np.int64(0)

In [56]:
f_p_df.isnull().sum()

product_id        0
product_name      0
category_id       0
price             0
stock_quantity    0
description       0
dtype: int64

### Data Cleaning Process in Orders DataFrame

In [63]:
f_o_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       18000 non-null  object
 1   customer_id    18000 non-null  object
 2   order_date     18000 non-null  object
 3   eta_days       18000 non-null  int64
 4   delivery_date  18000 non-null  object
 5   order_status   16426 non-null  object
 6   total_amount   18000 non-null  float64
dtypes: float64(1), int64(1), object(5)
memory usage: 984.5+ KB

In [66]:
f_o_df.dtypes

order_id          object
customer_id       object
order_date        object
eta_days           int64
delivery_date     object
order_status      object
total_amount     float64
dtype: object

In [67]:
# Correcting Data types
f_o_df['order_date'] = pd.to_datetime(f_o_df['order_date'])

f_o_df['delivery_date'] = pd.to_datetime(f_o_df['delivery_date'])

In [64]:
f_o_df.duplicated().sum()

np.int64(0)

In [65]:
f_o_df.isnull().sum()

order_id            0
customer_id         0
order_date          0
eta_days            0
delivery_date       0
order_status     1574
total_amount        0
dtype: int64

In [68]:
f_o_df['order_status'] = f_o_df['order_status'].fillna('Unknown')

In [69]:
f_o_df.isnull().sum()

order_id         0
customer_id      0
order_date       0
eta_days         0
delivery_date    0
order_status     0
total_amount     0
dtype: int64

### Data Cleaning Process in Ordered Items DataFrame

In [70]:
f_oi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  25000 non-null  object
 1   order_id       25000 non-null  object
 2   product_id     25000 non-null  object
 3   quantity       25000 non-null  int64
 4   unit_price     25000 non-null  float64
 5   total_price    25000 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ MB

In [71]:
f_oi_df.describe()

           quantity    unit_price    total_price
count  25000.000000  25000.000000   25000.000000
mean       3.008720   7944.463200   23888.689066
std        1.417887  16533.267043   55820.306593
min        1.000000     35.380000      35.380000
25%        2.000000    868.590000    2131.387500
50%        3.000000   2087.520000    5680.480000
75%        4.000000   6268.570000   17620.087500
max        5.000000  94685.550000  473427.750000

In [72]:
f_oi_df.duplicated().sum()

np.int64(0)

In [73]:
f_oi_df.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
total_price      0
dtype: int64

In [74]:
f_oi_df.dtypes

order_item_id     object
order_id          object
product_id        object
quantity           int64
unit_price       float64
total_price      float64
dtype: object

### Data Cleaning Process in Payments Items DataFrame

In [75]:
f_pay_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      18000 non-null  object
 1   order_id        18000 non-null  object
 2   payment_method  16333 non-null  object
 3   payment_date    18000 non-null  object
 4   payment_status  18000 non-null  object
dtypes: object(5)
memory usage: 703.3+ KB

In [76]:
f_pay_df.describe()

,payment_id,order_id,payment_method,payment_date,payment_status
count,18000,18000,16333,18000,18000
unique,18000,18000,5,11241,2
top,FPAY-400000,FORD-26-30000,Net Banking,2025-08-17 17:39:00,Completed
freq,1,1,3335,7,16092

In [77]:
f_pay_df.duplicated().sum()

np.int64(0)

In [78]:
f_pay_df.isnull().sum()

payment_id           0
order_id             0
payment_method    1667
payment_date         0
payment_status       0
dtype: int64

In [79]:
# 1. Calculate the probability distribution of existing payment methods
probabilities = f_pay_df['payment_method'].value_counts(normalize=True)

# 2. Count how many missing values need filling
num_nulls = f_pay_df['payment_method'].isna().sum()

# 3. Randomly sample payment methods matching the exact probability weights
sampled_payments = np.random.choice(probabilities.index, size=num_nulls, p=probabilities.values)

# 4. Fill the null entries
f_pay_df.loc[f_pay_df['payment_method'].isna(), 'payment_method'] = sampled_payments

In [80]:
f_pay_df.isnull().sum()

payment_id        0
order_id          0
payment_method    0
payment_date      0
payment_status    0
dtype: int64

### Data Cleaning Process in Reviews Items DataFrame

In [81]:
f_r_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    5986 non-null   object
 1   product_id   5986 non-null   object
 2   customer_id  5986 non-null   object
 3   rating       5452 non-null   float64
 4   review_text  5986 non-null   object
 5   review_date  5986 non-null   object
dtypes: float64(1), object(5)
memory usage: 280.7+ KB

In [83]:
f_r_df.dtypes

review_id       object
product_id      object
customer_id     object
rating         float64
review_text     object
review_date     object
dtype: object

In [85]:
f_r_df.describe()

            rating
count  5452.000000
mean      3.000917
std       1.410902
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       5.000000

In [86]:
a_r_df.dropna(subset=['rating'], inplace=True)

In [87]:
a_r_df.isnull().sum()

review_id      0
product_id     0
customer_id    0
rating         0
review_text    0
review_date    0
dtype: int64

In [92]:
# List of tuples containing (Amazon_df, Flipkart_df, Table_Name)
tables_to_merge = [(a_c_df, f_c_df, 'customers'),
                   (a_p_df, f_p_df, 'products'),
                   (a_cat_df, f_cat_df, 'categories'),
                   (a_o_df, f_o_df, 'orders'),
                   (a_oi_df, f_oi_df, 'order_items'),
                   (a_pay_df, f_pay_df, 'payments'),
                   (a_r_df, f_r_df, 'reviews')]

# Dictionary to hold our final merged dataframes
merged_dfs = {}

for amz, flp, name in tables_to_merge:
    # Add Platform column
    amz['platform'] = 'Amazon'
    flp['platform'] = 'Flipkart'
    
    # Concatenate and store in dictionary
    merged_dfs[name] = pd.concat([amz, flp], ignore_index=True)
    
    print(f"{name} merged successfully! Final shape: {merged_dfs[name].shape}")

customers merged successfully! Final shape: (21862, 9)
products merged successfully! Final shape: (5000, 7)
categories merged successfully! Final shape: (1000, 5)
orders merged successfully! Final shape: (36000, 8)
order_items merged successfully! Final shape: (50000, 7)
payments merged successfully! Final shape: (36000, 6)
reviews merged successfully! Final shape: (11417, 7)

In [93]:
import os

# 1. Define the name of your new folder
output_folder = "Merged_Ecomm_Data"

# 2. Create the folder if it does not already exist
os.makedirs(output_folder, exist_ok=True)

# 3. Export all merged tables to this specific folder
for name, df in merged_dfs.items():
    # Construct the full file path (e.g., 'Merged_Ecomm_Data/Combined_Customers.csv')
    file_path = os.path.join(output_folder, f"Combined_{name}.csv")
    
    # Save the CSV
    df.to_csv(file_path, index=False)
    print(f"Successfully saved to: {file_path}")

Successfully saved to: Merged_Ecomm_Data\Combined_customers.csv
Successfully saved to: Merged_Ecomm_Data\Combined_products.csv
Successfully saved to: Merged_Ecomm_Data\Combined_categories.csv
Successfully saved to: Merged_Ecomm_Data\Combined_orders.csv
Successfully saved to: Merged_Ecomm_Data\Combined_order_items.csv
Successfully saved to: Merged_Ecomm_Data\Combined_payments.csv
Successfully saved to: Merged_Ecomm_Data\Combined_reviews.csv

In [94]:
from sqlalchemy import create_engine

username = 'root'
password = '1234'
host = 'localhost'         
port = '3306'              
database = 'a_vs_f' 


connection_string = f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
engine = create_engine(connection_string)


for table_name, df in merged_dfs.items():
    
    # Prefix the table name so it is clear in your database
    sql_table_name = f"{table_name}"
    
    print(f"Uploading {sql_table_name} to MySQL... Please wait.")
    
    # Write the dataframe to SQL
    # if_exists='replace' will overwrite the table if you run the script multiple times
    # index=False prevents pandas from writing the row numbers as a column
    df.to_sql(name=sql_table_name, con=engine, if_exists='replace', index=False)
    
    print(f"Successfully uploaded {sql_table_name}!")

print("All 7 tables have been successfully pushed to your MySQL database!")

Uploading customers to MySQL... Please wait.
Successfully uploaded customers!
Uploading products to MySQL... Please wait.
Successfully uploaded products!
Uploading categories to MySQL... Please wait.
Successfully uploaded categories!
Uploading orders to MySQL... Please wait.
Successfully uploaded orders!
Uploading order_items to MySQL... Please wait.
Successfully uploaded order_items!
Uploading payments to MySQL... Please wait.
Successfully uploaded payments!
Uploading reviews to MySQL... Please wait.
Successfully uploaded reviews!
All 7 tables have been successfully pushed to your MySQL database!